server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA : renvoyer index.html pour toutes les routes non-fichier
    location / {
        try_files $uri $uri/ /index.html;
    }

    # proxy API vers le backend (docker compose network)
    location /api/ {
        proxy_pass http://backend:8000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # to pour les calculs
        proxy_connect_timeout 10s;
        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;

        # SSE : pas de buffer
        proxy_buffering off;
        proxy_cache off;
        proxy_set_header Connection '';
        chunked_transfer_encoding off;
    }

    # cache
    location ~* \.(js|css|png|jpg|svg|woff2?)$ {
        expires 7d;
        add_header Cache-Control "public, immutable";
    }
}
